name: Release

on:
  push:
    tags:
      - '*.*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: |
          mkdir dt-family-groups
          cp -r dt-family-groups.php admin js languages rest-api tile version-control.json LICENSE SECURITY.md dt-family-groups/
          zip -r dt-family-groups.zip dt-family-groups
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dt-family-groups.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
